age_text="21"
course_fee_text="499.90"
attempts=3
age=int(age_text)
course_fee=float(course_fee_text)
attempts=str(attempts)
print(age)
print(type(age))
print(course_fee)
print(type(course_fee))
print(attempts)
print(type(attempts))