course_name=input("enter the course name:")
current_week=input("enter the current week:")
course_status=input("enter the course status:-")
tuple=(course_name,current_week,course_status)
updated_week=input("enter the updated week:- ")
tuple=(course_name,updated_week,course_status)
print(tuple)
